In [19]:
# Import libraries
import pandas as pd
import numpy as np
import json

In [12]:
# Importing the two dataset provided by Deloitte
df_meta = pd.read_json("data/meta_Health_and_Personal_Care.json", lines=True) 
df_review = pd.read_json("data/Health_and_Personal_Care.json", lines=True)

In [13]:
# Analyzing the shape of both dataset
print("Meta shape:", df_meta.shape)
print("Review shape:", df_review.shape)

Meta shape: (60293, 14)
Review shape: (494121, 10)

In [14]:
# Checking the first rows of the two datasets
display(df_meta.head())

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Health & Personal Care,Silicone Bath Body Brush Exfoliator Shower Bac...,3.9,7,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Rzoeox,[],{'Package Dimensions': '15 x 3.3 x 1.5 inches;...,B07V346GZH,NaN
1,Health & Personal Care,"iPhone 7 Plus 8 Plus Screen Protector, ZHXIN T...",3.8,2,[Tough and Robust: Like all 78X screen protect...,[Features: 2.5D Arc Edge Treatment: The edge i...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZHXIN,[],"{'Brand': 'ZHXIN', 'Compatible Devices': 'Cell...",B075W927RH,NaN
2,Health & Personal Care,Zig Zag Rolling Machine 70mm Size With FREE BO...,3.9,7,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],NaN,[],{'Package Dimensions': '4.1 x 1.8 x 0.3 inches...,B01FB26VKY,NaN
3,Health & Personal Care,Sting-Kill Disposable Wipes 8 Each ( Pack of 5),4.1,6,[],"[effective on stings and bites from bees, wasp...",21.37,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sting-kill,[],"{'Brand': 'Sting-kill', 'Item Form': 'Wipe', '...",B01IAI29RU,NaN
4,Health & Personal Care,Heated Eyelash Curler Mini Portable Electric E...,3.3,8,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],BiBOSS,[],{'Package Dimensions': '6.1 x 3.1 x 1.9 inches...,B08CMN38RC,NaN

In [15]:
display(df_review.head())

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,12 mg is 12 on the periodic table people! Mg f...,This review is more to clarify someone else’s ...,[],B07TDSJZMR,B07TDSJZMR,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-02-06 00:49:35.902,3,True
1,5,Save the lanet using less plastic.,Love these easy multitasking bleach tablets. B...,[],B08637FWWF,B08637FWWF,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,2020-11-02 22:03:06.880,3,True
2,5,Fantastic,I have been suffering a couple months with hee...,[],B07KJVGNN5,B07KJVGNN5,AHSPLDNW5OOUK2PLH7GXLACFBZNQ,2019-07-24 11:13:58.905,0,True
3,4,It holds the water and makes bubbles. That's ...,"It's cheap and it does what I wanted. The ""ma...",[],B007HY7GC2,B092RP73CX,AEZGPLOYTSAPR3DHZKKXEFPAXUAA,2022-09-04 02:29:02.725,7,True
4,1,Not for me,Didn't do a thing for me. Not saying they don'...,[],B08KYJLF5T,B08KYJLF5T,AEQAYV7RXZEBXMQIQPL6KCT2CFWQ,2022-01-20 23:53:07.262,0,True

In [16]:
# Checking the datatypes
print(df_meta.dtypes)
print(df_review.dtypes)

main_category          str
title                  str
average_rating     float64
rating_number        int64
features            object
description         object
price              float64
images              object
videos              object
store                  str
categories          object
details             object
parent_asin            str
bought_together    float64
dtype: object
rating                        int64
title                           str
text                            str
images                       object
asin                            str
parent_asin                     str
user_id                         str
timestamp            datetime64[ms]
helpful_vote                  int64
verified_purchase              bool
dtype: object

In [17]:
# Checking for missing values
meta_missing = df_meta.isna().mean().sort_values(ascending=False)
review_missing = df_review.isna().mean().sort_values(ascending=False)

print("Missing meta:\n", meta_missing.head(15))
print("Missing review:\n", review_missing.head(15))

Missing meta:
 bought_together    1.000000
price              0.825253
store              0.038910
average_rating     0.000000
main_category      0.000000
title              0.000000
description        0.000000
features           0.000000
rating_number      0.000000
images             0.000000
videos             0.000000
categories         0.000000
details            0.000000
parent_asin        0.000000
dtype: float64
Missing review:
 rating               0.0
title                0.0
text                 0.0
images               0.0
asin                 0.0
parent_asin          0.0
user_id              0.0
timestamp            0.0
helpful_vote         0.0
verified_purchase    0.0
dtype: float64

***Understanding the missing value, other than the null value that are most present in price and in bought_together. We need to analyze even the value that don't have anything write***

In [20]:
# Converting all the missing value that are written as [] or {} to NaN

def empty_to_nan(x):
    if x == [] or x == {}:
        return np.nan
    return x

# pandas 3.0 removed `DataFrame.applymap`, so we fall back to applying
# the transformation on each column. This achieves the same element-wise
# behavior without relying on the removed method.

df_meta = df_meta.apply(lambda col: col.apply(empty_to_nan))
df_review = df_review.apply(lambda col: col.apply(empty_to_nan))

In [23]:
df_meta.replace("", np.nan, inplace=True)
df_review.replace("", np.nan, inplace=True)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,12 mg is 12 on the periodic table people! Mg f...,This review is more to clarify someone else’s ...,NaN,B07TDSJZMR,B07TDSJZMR,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-02-06 00:49:35.902,3,True
1,5,Save the lanet using less plastic.,Love these easy multitasking bleach tablets. B...,NaN,B08637FWWF,B08637FWWF,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,2020-11-02 22:03:06.880,3,True
2,5,Fantastic,I have been suffering a couple months with hee...,NaN,B07KJVGNN5,B07KJVGNN5,AHSPLDNW5OOUK2PLH7GXLACFBZNQ,2019-07-24 11:13:58.905,0,True
3,4,It holds the water and makes bubbles. That's ...,"It's cheap and it does what I wanted. The ""ma...",NaN,B007HY7GC2,B092RP73CX,AEZGPLOYTSAPR3DHZKKXEFPAXUAA,2022-09-04 02:29:02.725,7,True
4,1,Not for me,Didn't do a thing for me. Not saying they don'...,NaN,B08KYJLF5T,B08KYJLF5T,AEQAYV7RXZEBXMQIQPL6KCT2CFWQ,2022-01-20 23:53:07.262,0,True
...,...,...,...,...,...,...,...,...,...,...
494116,5,Best brush!,"Material is good. Worthy to buy.Firstly, the c...",NaN,B07KXT7Y48,B07KXT7Y48,AEQG5UEVYBNLWPXB3E2EODQ3EGSQ,2019-04-12 04:21:04.257,6,True
494117,5,It makes my skin softer.,This brush is a good tool for cleaning and mas...,NaN,B07KXT7Y48,B07KXT7Y48,AGTVLNJAFZTKURBCHLUIH6VEOQCQ,2020-07-17 05:01:39.190,0,True
494118,5,This brush is perfect !,"Honestly, the brush totally is 15inch. Maybe y...",[{'small_image_url': 'https://images-na.ssl-im...,B07KXT7Y48,B07KXT7Y48,AGMA5UN3JPLQLQZ2PFYHJYSC4PNA,2019-03-07 22:33:36.968,173,True
494119,5,Easy to use,"Easy to hold, soft and flexible.",NaN,B07KXT7Y48,B07KXT7Y48,AE2Q3FXHIVGSSDGTNI4YLXDXMCIA,2019-09-26 12:22:51.244,0,True
494120,5,La comunicación con la empresa y ez perfecto,Es como están en la foto,NaN,B07JYKP19X,B07JYKP19X,AH5K35CHSUC2QMGRMDQNXR6BJ72A,2019-10-03 01:03:59.311,0,True

In [24]:
meta_missing = df_meta.isna().mean().sort_values(ascending=False)
review_missing = df_review.isna().mean().sort_values(ascending=False)

print("Meta missing ratio:\n", meta_missing.head(20))
print("Review missing ratio:\n", review_missing.head(20))

Meta missing ratio:
 categories         1.000000
bought_together    1.000000
videos             0.863384
price              0.825253
features           0.740832
description        0.706765
store              0.038910
details            0.016403
title              0.000083
main_category      0.000000
average_rating     0.000000
rating_number      0.000000
images             0.000000
parent_asin        0.000000
dtype: float64
Review missing ratio:
 images               0.956972
text                 0.000055
title                0.000000
rating               0.000000
asin                 0.000000
parent_asin          0.000000
user_id              0.000000
timestamp            0.000000
helpful_vote         0.000000
verified_purchase    0.000000
dtype: float64